// ============================================================
// Hawaiʻi Dashboard - Off the Charts post index
//
// GENERATED FILE - do not hand-edit.
// Regenerated by scripts/sync-otc-meta.js from the post HTML
// (JSON-LD headline/datePublished + internal chart links).
//
// Consumed by:
//   - js/app.js   (homepage Off the Charts strip)
//   - js/modal.js (deep-dive "story behind this chart" link)
//   - js/qotd.js  (QOTD proof-view story link)
// Posts are ordered newest first; metrics[0] is the primary metric.
// ============================================================

const OTC_POSTS = [
    { slug: "common-incomes-uncommon-costs", title: "Common incomes. Uncommon costs.", date: "2026-06-14", metrics: ["gini_index","real_per_capita_income","home_price_to_income"] },
    { slug: "safe-state-theft-problem", title: "A safe state with a theft problem.", date: "2026-05-29", metrics: ["violent_crime_rate","property_crime_rate"] },
    { slug: "florida-rent-burden", title: "Florida has Hawaiʻi beat on rent burden.", date: "2026-05-27", metrics: ["home_price_to_income","renter_cost_burden_pct"] },
    { slug: "rainy-day-fund-rule", title: "Hawaiʻi has the rainy day fund, finally.", date: "2026-05-25", metrics: ["rainy_day_fund_pct"] },
    { slug: "low-violent-crime-high-homelessness", title: "Seventeen years of low violent crime with high homelessness.", date: "2026-05-17", metrics: ["unsheltered_homeless_rate","violent_crime_rate"] },
    { slug: "productivity-vs-unemployment", title: "One of America's tightest labor markets, with the weakest productivity growth.", date: "2026-05-12", metrics: ["unemployment_rate","labor_productivity"] },
    { slug: "reading-without-raising", title: "How Hawaiʻi rose in 8th-grade reading without raising its score.", date: "2026-05-09", metrics: ["naep_reading_8"] },
    { slug: "expensive-states", title: "Expensive states are rich. Not Hawaiʻi.", date: "2026-05-05", metrics: ["home_price_to_income","real_per_capita_income","net_domestic_migration_rate"] },
    { slug: "renewables-prices", title: "Hawaiʻi quadrupled its renewables. The energy prices got worse.", date: "2026-04-28", metrics: ["renewables_share_gen","residential_price_cpkwh"] }
];

/**
 * Best post for a dashboard metric slug, or null. Prefers the newest post
 * whose PRIMARY metric (metrics[0]) is the slug; falls back to the newest
 * post mentioning it at all. OTC_POSTS is already ordered newest first.
 */
function otcPostForMetric(slug) {
    return OTC_POSTS.find(p => p.metrics[0] === slug)
        || OTC_POSTS.find(p => p.metrics.indexOf(slug) !== -1)
        || null;
}

// Dual export: browser global + Node.js module (for unit tests)
if (typeof module !== 'undefined') module.exports = { OTC_POSTS, otcPostForMetric };
